export {
    NO_INTERACTION,
    PLAYER_INDEX_OFFSET,
    type InteractionIndex,
    type InteractionTargetType,
    clampInteractionIndex,
    decodeInteractionIndex,
    decodeInteractionTarget,
    encodeInteractionIndex,
    encodeInteractionTarget,
    isNpcInteractionIndex,
    isPlayerInteractionIndex,
    isValidInteractionIndex,
    resolveInteractionTargetId,
} from "../../../src/rs/interaction/InteractionIndex";
