export const INDEXED_MENU_GROUP_ID = 187;
export const INDEXED_MENU_SCRIPT_ID = 378;
export const INDEXED_MENU_KEYLISTENERS_COMPONENT_ID = 1;
export const INDEXED_MENU_SCROLLBAR_COMPONENT_ID = 2;
export const INDEXED_MENU_LIST_COMPONENT_ID = 3;

export const INDEXED_MENU_KEYLISTENERS_UID =
    (INDEXED_MENU_GROUP_ID << 16) | INDEXED_MENU_KEYLISTENERS_COMPONENT_ID;
export const INDEXED_MENU_LIST_UID = (INDEXED_MENU_GROUP_ID << 16) | INDEXED_MENU_LIST_COMPONENT_ID;

// Bit 0 = pause button / resume_pausebutton.
export const INDEXED_MENU_PAUSE_BUTTON_FLAGS = 1;
