import { SkillId } from "../../../../../src/rs/skill/skills";
import {
    AsgAreas,
    AsgCombat,
    CombatMonsterCb,
    ITEM_AIR_RUNE,
    ITEM_ANCHOVIES,
    ITEM_ASHES,
    ITEM_ATTACK_POTION3,
    ITEM_BONES,
    ITEM_BIG_BONES,
    ITEM_BREAD,
    ITEM_BRONZE_ARROW,
    ITEM_BRONZE_BAR,
    ITEM_BRONZE_DAGGER,
    ITEM_BRONZE_MED_HELM,
    ITEM_BRONZE_NAILS,
    ITEM_BRONZE_SWORD,
    ITEM_BUCKET_MILK,
    ITEM_CABBAGE,
    ITEM_COAL,
    ITEM_COPPER_ORE,
    ITEM_EGG,
    ITEM_EYE_OF_NEWT,
    ITEM_FIRE_RUNE,
    ITEM_IRON_ARROW,
    ITEM_IRON_BAR,
    ITEM_IRON_DAGGER,
    ITEM_IRON_ORE,
    ITEM_LETTER,
    ITEM_LOGS,
    ITEM_MIND_RUNE,
    ITEM_MITHRIL_ORE,
    ITEM_OAK_LOGS,
    ITEM_ONION,
    ITEM_PLANK,
    ITEM_POTATO,
    ITEM_PURE_ESSENCE,
    ITEM_RAW_ANCHOVIES,
    ITEM_RAW_SALMON,
    ITEM_RAW_SHRIMPS,
    ITEM_RAW_TROUT,
    ITEM_ROPE,
    ITEM_RUNE_ESSENCE,
    ITEM_SALMON,
    ITEM_SHRIMPS,
    ITEM_STEEL_BAR,
    ITEM_TIN_ORE,
    ITEM_TROUT,
    ITEM_VIAL_WATER,
    NPC_DISPLAY_NAMES,
    NpcIds,
} from "../constants";
import type { RegionalFavourDefinition, TileBounds } from "../types";

function npcLabel(npcId: number): string {
    return NPC_DISPLAY_NAMES[npcId] ?? `NPC ${npcId}`;
}

function speak(
    id: string,
    giver: number,
    target: number,
    name: string,
    travelDistance: number,
    difficulty: RegionalFavourDefinition["reward"]["difficulty"] = "very_easy",
): RegionalFavourDefinition {
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: target,
        category: "SPEAK_TO_NPC",
        reward: { kind: "skill_xp", skillId: SkillId.Agility, difficulty, travelDistance },
        targetNpcIds: [target],
        minAmount: 1,
        maxAmount: 1,
        baseWeight: 12,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: `Speak to ${name}.`,
        instructionText: `Find ${name} in Asgarnia and speak with them, then claim your reward.`,
        assignmentDialog: [
            `Could you find ${name} for me?`,
            "Just have a word with them and they'll sort you out.",
        ],
        completionDialog: ["Thanks for passing that along.", "Here's something for the walk."],
        recommendedSkillId: SkillId.Agility,
        recommendedLevelMin: 1,
        recommendedLevelMax: 99,
    };
}

function visit(
    id: string,
    giver: number,
    turnIn: number,
    area: TileBounds,
    label: string,
    travelDistance: number,
): RegionalFavourDefinition {
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: turnIn,
        category: "VISIT_LOCATION",
        reward: { kind: "skill_xp", skillId: SkillId.Agility, difficulty: "easy", travelDistance },
        targetArea: area,
        minAmount: 1,
        maxAmount: 1,
        baseWeight: 10,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: `Visit ${label}.`,
        instructionText: `Travel to ${label}, then return to claim your reward.`,
        assignmentDialog: [`I need someone to check on ${label}.`, "Go there, then come back."],
        completionDialog: ["Good work getting there.", "Take this for your travels."],
        recommendedSkillId: SkillId.Agility,
    };
}

function deliver(
    id: string,
    giver: number,
    turnIn: number,
    turnInName: string,
    travelDistance: number,
): RegionalFavourDefinition {
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: turnIn,
        category: "DELIVER_ITEM",
        reward: { kind: "skill_xp", skillId: SkillId.Agility, difficulty: "easy", travelDistance },
        deliveryItemId: ITEM_LETTER,
        targetItemId: ITEM_LETTER,
        minAmount: 1,
        maxAmount: 1,
        baseWeight: 14,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: `Deliver a letter to ${turnInName}.`,
        instructionText: `Take the letter to ${turnInName}. If you lose it, ask the favour giver to replace it.`,
        assignmentDialog: [
            `Take this letter to ${turnInName}.`,
            "Don't open it — just deliver it safely.",
        ],
        completionDialog: ["Ah, the letter. Thank you.", "Here's payment for the journey."],
        recommendedSkillId: SkillId.Agility,
    };
}

function gather(
    id: string,
    giver: number,
    itemId: number,
    label: string,
    minAmount: number,
    maxAmount: number,
    skillId: SkillId,
    minLevel: number,
    difficulty: RegionalFavourDefinition["reward"]["difficulty"],
    acceptsExisting = true,
): RegionalFavourDefinition {
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: giver,
        category: "GATHER_ITEM",
        reward: { kind: "skill_xp", skillId, difficulty },
        targetItemId: itemId,
        minAmount,
        maxAmount,
        requirements: minLevel > 1 ? [{ skillId, level: minLevel }] : undefined,
        baseWeight: 11,
        acceptsExistingItems: acceptsExisting,
        requiresPostAssignmentProgress: !acceptsExisting,
        objectiveText: `Bring ${label} to ${npcLabel(giver)}.`,
        instructionText: acceptsExisting
            ? `Gather ${label} and turn them in to ${npcLabel(giver)}.`
            : `Obtain ${label} after accepting this favour, then turn them in to ${npcLabel(giver)}.`,
        assignmentDialog: [
            `I need ${label}.`,
            `Bring them to ${npcLabel(giver)} when you have enough.`,
        ],
        completionDialog: ["Perfect, just what I needed.", "Here's your reward."],
        recommendedSkillId: skillId,
        recommendedLevelMin: minLevel,
        recommendedLevelMax: minLevel + 20,
    };
}

function produce(
    id: string,
    giver: number,
    itemId: number,
    label: string,
    minAmount: number,
    maxAmount: number,
    skillId: SkillId,
    minLevel: number,
    difficulty: RegionalFavourDefinition["reward"]["difficulty"],
): RegionalFavourDefinition {
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: giver,
        category: "PRODUCE_ITEM",
        reward: { kind: "skill_xp", skillId, difficulty },
        targetItemId: itemId,
        minAmount,
        maxAmount,
        requirements: [{ skillId, level: minLevel }],
        baseWeight: 10,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: `Produce ${label} for ${npcLabel(giver)}.`,
        instructionText: `Personally make ${label}, then turn them in to ${npcLabel(giver)}.`,
        assignmentDialog: [
            `Make me ${label} yourself.`,
            `Bring them to ${npcLabel(giver)} — I can tell if they're shop-bought.`,
        ],
        completionDialog: ["Fine work.", "Take this."],
        recommendedSkillId: skillId,
        recommendedLevelMin: minLevel,
        recommendedLevelMax: minLevel + 25,
    };
}

/**
 * Combat favour tiered by the monster's OSRS combat level.
 * recommended band stays tight around monsterCb so high-level players
 * are steered toward harder targets (Guards → Hill Giants → Ice Warriors…).
 */
function kill(
    id: string,
    giver: number,
    npcIds: readonly number[],
    label: string,
    minAmount: number,
    maxAmount: number,
    monsterCb: number,
    difficulty: RegionalFavourDefinition["reward"]["difficulty"],
): RegionalFavourDefinition {
    const minCombat = Math.max(1, monsterCb - 8);
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: giver,
        category: "KILL_NPC",
        reward: { kind: "combat_lamp", difficulty },
        targetNpcIds: [...npcIds],
        minAmount,
        maxAmount,
        minCombatLevel: minCombat,
        baseWeight: 12,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: `Kill ${label}.`,
        instructionText: `Defeat ${label} in Asgarnia after accepting this favour, then return.`,
        assignmentDialog: [`We've had trouble with ${label}.`, "Deal with them, then report back."],
        completionDialog: [
            "The area should be safer now.",
            "Take these coins and a combat lamp for your efforts.",
        ],
        recommendedLevelMin: Math.max(1, monsterCb - 2),
        recommendedLevelMax: monsterCb + 12,
    };
}

function bury(
    id: string,
    giver: number,
    itemId: number,
    label: string,
    minAmount: number,
    maxAmount: number,
    minPrayer: number,
): RegionalFavourDefinition {
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: giver,
        category: "BURY_OR_OFFER_BONES",
        reward: { kind: "skill_xp", skillId: SkillId.Prayer, difficulty: "easy" },
        targetItemId: itemId,
        minAmount,
        maxAmount,
        requirements: minPrayer > 1 ? [{ skillId: SkillId.Prayer, level: minPrayer }] : undefined,
        baseWeight: 9,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: `Bury ${label}.`,
        instructionText: `Bury ${label} after accepting this favour.`,
        assignmentDialog: [`The dead deserve rest.`, `Bury ${label} for me.`],
        completionDialog: ["You've shown respect.", "A small Prayer blessing for you."],
        recommendedSkillId: SkillId.Prayer,
        recommendedLevelMin: minPrayer,
        recommendedLevelMax: minPrayer + 20,
    };
}

function skillAct(
    id: string,
    giver: number,
    actionIds: readonly string[],
    area: TileBounds,
    label: string,
    skillId: SkillId,
    minLevel: number,
    difficulty: RegionalFavourDefinition["reward"]["difficulty"],
    opts?: {
        amount?: [number, number];
        objectNames?: readonly string[];
        turnIn?: number;
        travelDistance?: number;
    },
): RegionalFavourDefinition {
    const [minAmount, maxAmount] = opts?.amount ?? [1, 1];
    const turnIn = opts?.turnIn ?? giver;
    return {
        id,
        region: "asgarnia",
        giverNpcId: giver,
        turnInNpcId: turnIn,
        category: "PERFORM_SKILL_ACTION",
        reward: {
            kind: "skill_xp",
            skillId,
            difficulty,
            travelDistance: opts?.travelDistance,
        },
        skillActionIds: [...actionIds],
        targetArea: area,
        targetObjectNames: opts?.objectNames ? [...opts.objectNames] : undefined,
        minAmount,
        maxAmount,
        requirements: minLevel > 1 ? [{ skillId, level: minLevel }] : undefined,
        baseWeight: 11,
        acceptsExistingItems: false,
        requiresPostAssignmentProgress: true,
        objectiveText: label,
        instructionText: `${label} after accepting this favour, then return.`,
        assignmentDialog: [label, "Come back when it's done."],
        completionDialog: ["Nice work.", "Here's your reward."],
        recommendedSkillId: skillId,
        recommendedLevelMin: minLevel,
        recommendedLevelMax: minLevel + 20,
    };
}

const SQ = NpcIds.Squire;
const AMIK = NpcIds.SirAmikVarze;
const TIFFY = NpcIds.SirTiffyCashien;
const VYVIN = NpcIds.SirVyvin;
const RENITEE = NpcIds.SirRenitee;
const DORIC = NpcIds.Doric;
const WYSON = NpcIds.WysonTheGardener;
const SANFEW = NpcIds.Sanfew;
const KAQE = NpcIds.Kaqemeex;
const JATIX = NpcIds.Jatix;
const LADY = NpcIds.LadyOfTheLake;
const DENULTH = NpcIds.Denulth;
const TENZING = NpcIds.Tenzing;
const DUNSTAN = NpcIds.Dunstan;
const GAMFRED = NpcIds.Gamfred;
const TOBIAS = NpcIds.CaptainTobias;
const VEOS = NpcIds.Veos;
const REDBEARD = NpcIds.RedbeardFrank;
const BETTY = NpcIds.Betty;
const GERRANT = NpcIds.Gerrant;
const BRIAN = NpcIds.BrianPortSarim;
const WYDIN = NpcIds.Wydin;
const HETTY = NpcIds.Hetty;
const PHIALS = NpcIds.Phials;
const ORACLE = NpcIds.Oracle;
const ACHIETTIES = NpcIds.Achietties;
const CASSIE = NpcIds.Cassie;
const HAIR = NpcIds.Hairdresser;
const MAKEOVER = NpcIds.MakeoverMage;

export const ASGARNIA_FAVOUR_DEFINITIONS: RegionalFavourDefinition[] = [
    // ——— Squire (regional contact / general errands) ———
    speak("asg_squire_speak_amik", SQ, AMIK, "Sir Amik Varze", 20),
    speak("asg_squire_speak_vyvin", SQ, VYVIN, "Sir Vyvin", 25),
    speak("asg_squire_speak_tiffy", SQ, TIFFY, "Sir Tiffy Cashien", 40),
    speak("asg_squire_speak_doric", SQ, DORIC, "Doric", 180),
    speak("asg_squire_speak_wyson", SQ, WYSON, "Wyson the Gardener", 60),
    deliver("asg_squire_letter_amik", SQ, AMIK, "Sir Amik Varze", 20),
    deliver("asg_squire_letter_tobias", SQ, TOBIAS, "Captain Tobias", 220),
    deliver("asg_squire_letter_denulth", SQ, DENULTH, "Commander Denulth", 320),
    deliver("asg_squire_letter_betty", SQ, BETTY, "Betty", 200),
    visit("asg_squire_visit_park", SQ, SQ, AsgAreas.FaladorPark, "Falador Park", 50),
    visit("asg_squire_visit_port", SQ, SQ, AsgAreas.PortSarim, "Port Sarim", 200),
    visit("asg_squire_visit_taverley", SQ, SQ, AsgAreas.Taverley, "Taverley", 220),
    visit("asg_squire_visit_ice", SQ, SQ, AsgAreas.IceMountain, "Ice Mountain", 250),
    kill("asg_squire_kill_goblins", SQ, AsgCombat.Goblins, "goblins", 5, 15, CombatMonsterCb.Goblin, "easy"),
    kill("asg_squire_kill_imps", SQ, AsgCombat.Imps, "imps", 3, 8, CombatMonsterCb.Imp, "easy"),
    kill("asg_squire_kill_guards", SQ, AsgCombat.Guards, "Falador guards", 3, 10, CombatMonsterCb.Guard, "medium"),
    kill("asg_squire_kill_black_knights", SQ, AsgCombat.BlackKnights, "Black Knights", 3, 8, CombatMonsterCb.BlackKnight, "medium"),
    bury("asg_squire_bury_bones", SQ, ITEM_BONES, "bones", 5, 15, 1),
    gather("asg_squire_logs", SQ, ITEM_LOGS, "logs", 5, 15, SkillId.Woodcutting, 1, "easy", false),

    // ——— Sir Amik Varze (military / diplomacy) ———
    speak("asg_amik_speak_squire", AMIK, SQ, "the Squire", 20),
    speak("asg_amik_speak_vyvin", AMIK, VYVIN, "Sir Vyvin", 20),
    speak("asg_amik_speak_tiffy", AMIK, TIFFY, "Sir Tiffy Cashien", 40),
    speak("asg_amik_speak_renitee", AMIK, RENITEE, "Sir Renitee", 25),
    speak("asg_amik_speak_denulth", AMIK, DENULTH, "Commander Denulth", 320),
    deliver("asg_amik_letter_denulth", AMIK, DENULTH, "Commander Denulth", 320),
    deliver("asg_amik_letter_tobias", AMIK, TOBIAS, "Captain Tobias", 220),
    deliver("asg_amik_letter_tiffy", AMIK, TIFFY, "Sir Tiffy Cashien", 40),
    visit("asg_amik_visit_fortress", AMIK, AMIK, AsgAreas.BlackKnightsFortress, "the Black Knights' Fortress", 280),
    visit("asg_amik_visit_burthorpe", AMIK, AMIK, AsgAreas.Burthorpe, "Burthorpe", 320),
    visit("asg_amik_visit_heroes", AMIK, AMIK, AsgAreas.HeroesGuild, "the Heroes' Guild", 280),
    kill("asg_amik_guards", AMIK, AsgCombat.Guards, "Falador guards", 5, 12, CombatMonsterCb.Guard, "medium"),
    kill("asg_amik_black_knights", AMIK, AsgCombat.BlackKnights, "Black Knights", 5, 12, CombatMonsterCb.BlackKnight, "medium"),
    kill("asg_amik_monks", AMIK, AsgCombat.MonksOfZamorak, "Monks of Zamorak", 3, 8, CombatMonsterCb.MonkOfZamorak, "medium"),
    kill("asg_amik_imps", AMIK, AsgCombat.Imps, "imps", 3, 10, CombatMonsterCb.Imp, "easy"),
    kill("asg_amik_goblins", AMIK, AsgCombat.Goblins, "goblins", 8, 20, CombatMonsterCb.Goblin, "easy"),
    gather("asg_amik_iron_bars", AMIK, ITEM_IRON_BAR, "iron bars", 3, 8, SkillId.Smithing, 15, "medium"),
    gather("asg_amik_steel_bars", AMIK, ITEM_STEEL_BAR, "steel bars", 2, 6, SkillId.Smithing, 30, "hard"),
    gather("asg_amik_arrows", AMIK, ITEM_IRON_ARROW, "iron arrows", 20, 50, SkillId.Fletching, 15, "medium"),

    // ——— Sir Tiffy Cashien (Temple Knights / investigations) ———
    speak("asg_tiffy_speak_amik", TIFFY, AMIK, "Sir Amik Varze", 40),
    speak("asg_tiffy_speak_squire", TIFFY, SQ, "the Squire", 40),
    speak("asg_tiffy_speak_oracle", TIFFY, ORACLE, "the Oracle", 220),
    speak("asg_tiffy_speak_achietties", TIFFY, ACHIETTIES, "Achietties", 250),
    deliver("asg_tiffy_letter_amik", TIFFY, AMIK, "Sir Amik Varze", 40),
    deliver("asg_tiffy_letter_denulth", TIFFY, DENULTH, "Commander Denulth", 280),
    deliver("asg_tiffy_letter_sanfew", TIFFY, SANFEW, "Sanfew", 180),
    visit("asg_tiffy_visit_ice", TIFFY, TIFFY, AsgAreas.IceMountain, "Ice Mountain", 200),
    visit("asg_tiffy_visit_fortress", TIFFY, TIFFY, AsgAreas.BlackKnightsFortress, "the Black Knights' Fortress", 220),
    visit("asg_tiffy_visit_port", TIFFY, TIFFY, AsgAreas.PortSarim, "Port Sarim", 180),
    kill("asg_tiffy_black_knights", TIFFY, AsgCombat.BlackKnights, "Black Knights", 5, 12, CombatMonsterCb.BlackKnight, "medium"),
    kill("asg_tiffy_dark_wizards", TIFFY, AsgCombat.DarkWizards, "dark wizards", 5, 12, CombatMonsterCb.DarkWizard, "medium"),
    kill("asg_tiffy_ice_warriors", TIFFY, AsgCombat.IceWarriors, "ice warriors", 3, 8, CombatMonsterCb.IceWarrior, "hard"),
    kill("asg_tiffy_ice_giants", TIFFY, AsgCombat.IceGiants, "ice giants", 3, 6, CombatMonsterCb.IceGiant, "hard"),
    kill("asg_tiffy_imps", TIFFY, AsgCombat.Imps, "imps", 3, 10, CombatMonsterCb.Imp, "easy"),
    kill("asg_tiffy_highwaymen", TIFFY, AsgCombat.Highwaymen, "highwaymen", 3, 8, CombatMonsterCb.Highwayman, "medium"),
    gather("asg_tiffy_air", TIFFY, ITEM_AIR_RUNE, "air runes", 20, 40, SkillId.Magic, 1, "easy"),
    gather("asg_tiffy_mind", TIFFY, ITEM_MIND_RUNE, "mind runes", 20, 40, SkillId.Magic, 1, "easy"),

    // ——— Doric (mining / smithing) ———
    gather("asg_doric_copper", DORIC, ITEM_COPPER_ORE, "copper ore", 5, 15, SkillId.Mining, 1, "easy", false),
    gather("asg_doric_tin", DORIC, ITEM_TIN_ORE, "tin ore", 5, 15, SkillId.Mining, 1, "easy", false),
    gather("asg_doric_iron", DORIC, ITEM_IRON_ORE, "iron ore", 5, 15, SkillId.Mining, 15, "medium", false),
    gather("asg_doric_coal", DORIC, ITEM_COAL, "coal", 5, 12, SkillId.Mining, 30, "medium", false),
    gather("asg_doric_mithril", DORIC, ITEM_MITHRIL_ORE, "mithril ore", 3, 8, SkillId.Mining, 55, "hard", false),
    gather("asg_doric_bronze_bars", DORIC, ITEM_BRONZE_BAR, "bronze bars", 3, 10, SkillId.Smithing, 1, "easy"),
    gather("asg_doric_iron_bars", DORIC, ITEM_IRON_BAR, "iron bars", 3, 8, SkillId.Smithing, 15, "medium"),
    produce("asg_doric_bronze_dagger", DORIC, ITEM_BRONZE_DAGGER, "bronze daggers", 1, 5, SkillId.Smithing, 1, "easy"),
    produce("asg_doric_bronze_sword", DORIC, ITEM_BRONZE_SWORD, "bronze swords", 1, 4, SkillId.Smithing, 4, "easy"),
    produce("asg_doric_bronze_helm", DORIC, ITEM_BRONZE_MED_HELM, "bronze medium helms", 1, 4, SkillId.Smithing, 3, "easy"),
    produce("asg_doric_iron_dagger", DORIC, ITEM_IRON_DAGGER, "iron daggers", 1, 4, SkillId.Smithing, 15, "medium"),
    deliver("asg_doric_to_dunstan", DORIC, DUNSTAN, "Dunstan", 220),
    deliver("asg_doric_to_amik", DORIC, AMIK, "Sir Amik Varze", 180),
    speak("asg_doric_speak_dunstan", DORIC, DUNSTAN, "Dunstan", 220),
    speak("asg_doric_speak_squire", DORIC, SQ, "the Squire", 180),
    kill("asg_doric_scorpions", DORIC, AsgCombat.Scorpions, "scorpions", 5, 12, CombatMonsterCb.Scorpion, "easy"),
    kill("asg_doric_hill_giants", DORIC, AsgCombat.HillGiants, "hill giants in Taverley Dungeon", 3, 8, CombatMonsterCb.HillGiant, "medium"),
    kill("asg_doric_hobgoblins", DORIC, AsgCombat.Hobgoblins, "hobgoblins", 3, 8, CombatMonsterCb.Hobgoblin, "medium"),
    kill("asg_doric_dwarves", DORIC, AsgCombat.Dwarves, "hostile dwarves", 3, 8, CombatMonsterCb.Dwarf, "easy"),
    visit("asg_doric_mining_guild", DORIC, DORIC, AsgAreas.MiningGuildEntrance, "the Mining Guild entrance", 120),

    // ——— Sanfew (herblore / druids) ———
    gather("asg_sanfew_vials", SANFEW, ITEM_VIAL_WATER, "vials of water", 3, 10, SkillId.Herblore, 1, "very_easy"),
    gather("asg_sanfew_eye", SANFEW, ITEM_EYE_OF_NEWT, "eyes of newt", 3, 10, SkillId.Herblore, 1, "easy"),
    gather("asg_sanfew_onions", SANFEW, ITEM_ONION, "onions", 5, 12, SkillId.Farming, 1, "very_easy"),
    produce("asg_sanfew_attack_pot", SANFEW, ITEM_ATTACK_POTION3, "attack potions", 1, 3, SkillId.Herblore, 3, "easy"),
    speak("asg_sanfew_kaqe", SANFEW, KAQE, "Kaqemeex", 80),
    speak("asg_sanfew_jatix", SANFEW, JATIX, "Jatix", 20),
    speak("asg_sanfew_lady", SANFEW, LADY, "the Lady of the Lake", 60),
    deliver("asg_sanfew_to_kaqe", SANFEW, KAQE, "Kaqemeex", 80),
    deliver("asg_sanfew_to_hetty", SANFEW, HETTY, "Hetty", 280),
    deliver("asg_sanfew_to_betty", SANFEW, BETTY, "Betty", 260),
    visit("asg_sanfew_circle", SANFEW, SANFEW, AsgAreas.DruidCircle, "the stone circle", 70),
    visit("asg_sanfew_dungeon", SANFEW, SANFEW, AsgAreas.TaverleyDungeonEntrance, "the Taverley Dungeon entrance", 40),
    kill("asg_sanfew_spiders", SANFEW, AsgCombat.Spiders, "spiders", 5, 12, CombatMonsterCb.Spider, "easy"),
    kill("asg_sanfew_rats", SANFEW, AsgCombat.GiantRats, "giant rats", 5, 12, CombatMonsterCb.GiantRat, "easy"),
    kill("asg_sanfew_skeletons", SANFEW, AsgCombat.Skeletons, "skeletons", 5, 12, CombatMonsterCb.Skeleton, "medium"),
    kill("asg_sanfew_hill_giants", SANFEW, AsgCombat.HillGiants, "hill giants in Taverley Dungeon", 3, 8, CombatMonsterCb.HillGiant, "medium"),
    bury("asg_sanfew_bury", SANFEW, ITEM_BONES, "bones", 5, 15, 1),

    // ——— Kaqemeex (nature / herblore) ———
    speak("asg_kaqe_speak_sanfew", KAQE, SANFEW, "Sanfew", 80),
    speak("asg_kaqe_speak_jatix", KAQE, JATIX, "Jatix", 80),
    speak("asg_kaqe_speak_lady", KAQE, LADY, "the Lady of the Lake", 50),
    deliver("asg_kaqe_to_sanfew", KAQE, SANFEW, "Sanfew", 80),
    deliver("asg_kaqe_to_wyson", KAQE, WYSON, "Wyson the Gardener", 160),
    visit("asg_kaqe_circle", KAQE, KAQE, AsgAreas.DruidCircle, "the stone circle", 20),
    visit("asg_kaqe_taverley", KAQE, KAQE, AsgAreas.Taverley, "Taverley", 40),
    gather("asg_kaqe_logs", KAQE, ITEM_LOGS, "logs", 5, 15, SkillId.Woodcutting, 1, "easy", false),
    gather("asg_kaqe_oak", KAQE, ITEM_OAK_LOGS, "oak logs", 5, 12, SkillId.Woodcutting, 15, "medium", false),
    gather("asg_kaqe_vials", KAQE, ITEM_VIAL_WATER, "vials of water", 3, 10, SkillId.Herblore, 1, "very_easy"),
    gather("asg_kaqe_potato", KAQE, ITEM_POTATO, "potatoes", 5, 15, SkillId.Farming, 1, "very_easy"),
    gather("asg_kaqe_cabbage", KAQE, ITEM_CABBAGE, "cabbages", 5, 12, SkillId.Farming, 1, "very_easy"),
    kill("asg_kaqe_imps", KAQE, AsgCombat.Imps, "imps", 3, 10, CombatMonsterCb.Imp, "easy"),
    kill("asg_kaqe_icefiends", KAQE, AsgCombat.Icefiends, "icefiends on Ice Mountain", 3, 8, CombatMonsterCb.Icefiend, "easy"),
    kill("asg_kaqe_spiders", KAQE, AsgCombat.Spiders, "spiders near the circle", 5, 12, CombatMonsterCb.Spider, "easy"),

    // ——— Commander Denulth (combat / defense) ———
    speak("asg_denulth_speak_dunstan", DENULTH, DUNSTAN, "Dunstan", 60),
    speak("asg_denulth_speak_tenzing", DENULTH, TENZING, "Tenzing", 100),
    speak("asg_denulth_speak_gamfred", DENULTH, GAMFRED, "Gamfred", 50),
    speak("asg_denulth_speak_amik", DENULTH, AMIK, "Sir Amik Varze", 320),
    deliver("asg_denulth_letter_amik", DENULTH, AMIK, "Sir Amik Varze", 320),
    deliver("asg_denulth_letter_dunstan", DENULTH, DUNSTAN, "Dunstan", 60),
    visit("asg_denulth_warriors", DENULTH, DENULTH, AsgAreas.WarriorsGuild, "the Warriors' Guild", 80),
    visit("asg_denulth_heroes", DENULTH, DENULTH, AsgAreas.HeroesGuild, "the Heroes' Guild", 60),
    visit("asg_denulth_ice", DENULTH, DENULTH, AsgAreas.IceMountain, "Ice Mountain", 180),
    kill("asg_denulth_trolls", DENULTH, AsgCombat.MountainTrolls, "mountain trolls", 5, 12, CombatMonsterCb.MountainTroll, "hard"),
    kill("asg_denulth_guards", DENULTH, AsgCombat.Guards, "Burthorpe guards", 3, 10, CombatMonsterCb.Guard, "medium"),
    kill("asg_denulth_goblins", DENULTH, AsgCombat.Goblins, "goblins", 8, 20, CombatMonsterCb.Goblin, "easy"),
    kill("asg_denulth_imps", DENULTH, AsgCombat.Imps, "imps", 3, 10, CombatMonsterCb.Imp, "easy"),
    kill("asg_denulth_hobgoblins", DENULTH, AsgCombat.Hobgoblins, "hobgoblins", 5, 12, CombatMonsterCb.Hobgoblin, "medium"),
    gather("asg_denulth_iron_bars", DENULTH, ITEM_IRON_BAR, "iron bars", 3, 8, SkillId.Smithing, 15, "medium"),
    gather("asg_denulth_arrows", DENULTH, ITEM_BRONZE_ARROW, "bronze arrows", 20, 50, SkillId.Fletching, 1, "easy"),
    bury("asg_denulth_bury", DENULTH, ITEM_BONES, "bones", 8, 20, 1),

    // ——— Dunstan (smithing) ———
    gather("asg_dunstan_copper", DUNSTAN, ITEM_COPPER_ORE, "copper ore", 5, 15, SkillId.Mining, 1, "easy", false),
    gather("asg_dunstan_iron", DUNSTAN, ITEM_IRON_ORE, "iron ore", 5, 15, SkillId.Mining, 15, "medium", false),
    gather("asg_dunstan_coal", DUNSTAN, ITEM_COAL, "coal", 5, 12, SkillId.Mining, 30, "medium", false),
    gather("asg_dunstan_bronze_bars", DUNSTAN, ITEM_BRONZE_BAR, "bronze bars", 3, 10, SkillId.Smithing, 1, "easy"),
    gather("asg_dunstan_iron_bars", DUNSTAN, ITEM_IRON_BAR, "iron bars", 3, 8, SkillId.Smithing, 15, "medium"),
    gather("asg_dunstan_steel_bars", DUNSTAN, ITEM_STEEL_BAR, "steel bars", 2, 6, SkillId.Smithing, 30, "hard"),
    produce("asg_dunstan_bronze_dagger", DUNSTAN, ITEM_BRONZE_DAGGER, "bronze daggers", 1, 5, SkillId.Smithing, 1, "easy"),
    produce("asg_dunstan_iron_dagger", DUNSTAN, ITEM_IRON_DAGGER, "iron daggers", 1, 4, SkillId.Smithing, 15, "medium"),
    gather("asg_dunstan_nails", DUNSTAN, ITEM_BRONZE_NAILS, "bronze nails", 10, 40, SkillId.Smithing, 1, "easy"),
    speak("asg_dunstan_denulth", DUNSTAN, DENULTH, "Commander Denulth", 60),
    speak("asg_dunstan_doric", DUNSTAN, DORIC, "Doric", 220),
    deliver("asg_dunstan_to_denulth", DUNSTAN, DENULTH, "Commander Denulth", 60),
    deliver("asg_dunstan_to_doric", DUNSTAN, DORIC, "Doric", 220),
    kill("asg_dunstan_trolls", DUNSTAN, AsgCombat.MountainTrolls, "mountain trolls", 3, 8, CombatMonsterCb.MountainTroll, "hard"),
    kill("asg_dunstan_hill_giants", DUNSTAN, AsgCombat.HillGiants, "hill giants", 3, 8, CombatMonsterCb.HillGiant, "medium"),
    kill("asg_dunstan_goblins", DUNSTAN, AsgCombat.Goblins, "goblins", 5, 15, CombatMonsterCb.Goblin, "easy"),

    // ——— Captain Tobias (travel / shipping) ———
    speak("asg_tobias_speak_redbeard", TOBIAS, REDBEARD, "Redbeard Frank", 40),
    speak("asg_tobias_speak_gerrant", TOBIAS, GERRANT, "Gerrant", 30),
    speak("asg_tobias_speak_wydin", TOBIAS, WYDIN, "Wydin", 30),
    speak("asg_tobias_speak_veos", TOBIAS, VEOS, "Veos", 40),
    speak("asg_tobias_speak_amik", TOBIAS, AMIK, "Sir Amik Varze", 220),
    deliver("asg_tobias_letter_amik", TOBIAS, AMIK, "Sir Amik Varze", 220),
    deliver("asg_tobias_letter_redbeard", TOBIAS, REDBEARD, "Redbeard Frank", 40),
    deliver("asg_tobias_letter_betty", TOBIAS, BETTY, "Betty", 50),
    visit("asg_tobias_docks", TOBIAS, TOBIAS, AsgAreas.PortSarimDocks, "the Port Sarim docks", 20),
    visit("asg_tobias_rimmington", TOBIAS, TOBIAS, AsgAreas.Rimmington, "Rimmington", 80),
    visit("asg_tobias_falador", TOBIAS, TOBIAS, AsgAreas.FaladorSquare, "Falador", 200),
    gather("asg_tobias_planks", TOBIAS, ITEM_PLANK, "planks", 3, 10, SkillId.Construction, 1, "easy"),
    gather("asg_tobias_rope", TOBIAS, ITEM_ROPE, "rope", 1, 5, SkillId.Crafting, 1, "easy"),
    gather("asg_tobias_nails", TOBIAS, ITEM_BRONZE_NAILS, "bronze nails", 10, 30, SkillId.Smithing, 1, "easy"),
    kill("asg_tobias_pirates", TOBIAS, AsgCombat.Pirates, "pirates", 3, 8, CombatMonsterCb.Pirate, "medium"),
    kill("asg_tobias_imps", TOBIAS, AsgCombat.Imps, "imps", 3, 8, CombatMonsterCb.Imp, "easy"),

    // ——— Redbeard Frank (pirates / deliveries / scavenging) ———
    speak("asg_redbeard_speak_tobias", REDBEARD, TOBIAS, "Captain Tobias", 40),
    speak("asg_redbeard_speak_wydin", REDBEARD, WYDIN, "Wydin", 40),
    speak("asg_redbeard_speak_betty", REDBEARD, BETTY, "Betty", 30),
    speak("asg_redbeard_speak_hetty", REDBEARD, HETTY, "Hetty", 80),
    deliver("asg_redbeard_letter_tobias", REDBEARD, TOBIAS, "Captain Tobias", 40),
    deliver("asg_redbeard_letter_wydin", REDBEARD, WYDIN, "Wydin", 40),
    deliver("asg_redbeard_letter_phials", REDBEARD, PHIALS, "Phials", 90),
    gather("asg_redbeard_shrimp", REDBEARD, ITEM_RAW_SHRIMPS, "raw shrimp", 5, 15, SkillId.Fishing, 1, "easy", false),
    gather("asg_redbeard_anchovies", REDBEARD, ITEM_RAW_ANCHOVIES, "raw anchovies", 5, 12, SkillId.Fishing, 15, "easy", false),
    gather("asg_redbeard_logs", REDBEARD, ITEM_LOGS, "logs", 5, 15, SkillId.Woodcutting, 1, "easy", false),
    gather("asg_redbeard_rope", REDBEARD, ITEM_ROPE, "rope", 1, 5, SkillId.Crafting, 1, "easy"),
    kill("asg_redbeard_pirates", REDBEARD, AsgCombat.Pirates, "rival pirates", 3, 8, CombatMonsterCb.Pirate, "medium"),
    kill("asg_redbeard_rats", REDBEARD, AsgCombat.Rats, "rats", 5, 15, CombatMonsterCb.Rat, "very_easy"),
    kill("asg_redbeard_imps", REDBEARD, AsgCombat.Imps, "imps", 3, 8, CombatMonsterCb.Imp, "easy"),
    kill("asg_redbeard_muggers", REDBEARD, AsgCombat.Muggers, "muggers", 3, 8, CombatMonsterCb.Mugger, "easy"),
    visit("asg_redbeard_rimmington", REDBEARD, REDBEARD, AsgAreas.Rimmington, "Rimmington", 80),

    // ——— Betty (magic) ———
    gather("asg_betty_air", BETTY, ITEM_AIR_RUNE, "air runes", 20, 50, SkillId.Runecraft, 1, "easy"),
    gather("asg_betty_mind", BETTY, ITEM_MIND_RUNE, "mind runes", 20, 50, SkillId.Runecraft, 2, "easy"),
    gather("asg_betty_fire", BETTY, ITEM_FIRE_RUNE, "fire runes", 20, 40, SkillId.Runecraft, 14, "medium"),
    gather("asg_betty_essence", BETTY, ITEM_RUNE_ESSENCE, "rune essence", 10, 30, SkillId.Mining, 1, "easy", false),
    gather("asg_betty_eye", BETTY, ITEM_EYE_OF_NEWT, "eyes of newt", 3, 10, SkillId.Magic, 1, "easy"),
    gather("asg_betty_ashes", BETTY, ITEM_ASHES, "ashes", 5, 12, SkillId.Firemaking, 1, "easy"),
    speak("asg_betty_speak_hetty", BETTY, HETTY, "Hetty", 80),
    speak("asg_betty_speak_sanfew", BETTY, SANFEW, "Sanfew", 260),
    speak("asg_betty_speak_oracle", BETTY, ORACLE, "the Oracle", 280),
    deliver("asg_betty_to_hetty", BETTY, HETTY, "Hetty", 80),
    deliver("asg_betty_to_sanfew", BETTY, SANFEW, "Sanfew", 260),
    visit("asg_betty_air_ruins", BETTY, BETTY, AsgAreas.AirAltarRuins, "the Air Altar ruins", 100),
    visit("asg_betty_mind_ruins", BETTY, BETTY, AsgAreas.MindAltarRuins, "the Mind Altar ruins", 280),
    visit("asg_betty_body_ruins", BETTY, BETTY, AsgAreas.BodyAltarRuins, "the Body Altar ruins", 260),
    kill("asg_betty_imps", BETTY, AsgCombat.Imps, "imps", 3, 10, CombatMonsterCb.Imp, "easy"),
    kill("asg_betty_dark_wizards", BETTY, AsgCombat.DarkWizards, "dark wizards", 5, 12, CombatMonsterCb.DarkWizard, "medium"),
    kill("asg_betty_ice_warriors", BETTY, AsgCombat.IceWarriors, "ice warriors", 3, 8, CombatMonsterCb.IceWarrior, "hard"),
    kill("asg_betty_ice_giants", BETTY, AsgCombat.IceGiants, "ice giants", 2, 5, CombatMonsterCb.IceGiant, "hard"),

    // ——— Gerrant (fishing) ———
    gather("asg_gerrant_shrimp", GERRANT, ITEM_RAW_SHRIMPS, "raw shrimp", 5, 20, SkillId.Fishing, 1, "easy", false),
    gather("asg_gerrant_anchovies", GERRANT, ITEM_RAW_ANCHOVIES, "raw anchovies", 5, 15, SkillId.Fishing, 15, "easy", false),
    gather("asg_gerrant_trout", GERRANT, ITEM_RAW_TROUT, "raw trout", 5, 15, SkillId.Fishing, 20, "medium", false),
    gather("asg_gerrant_salmon", GERRANT, ITEM_RAW_SALMON, "raw salmon", 5, 12, SkillId.Fishing, 30, "medium", false),
    produce("asg_gerrant_cook_shrimp", GERRANT, ITEM_SHRIMPS, "cooked shrimp", 5, 15, SkillId.Cooking, 1, "easy"),
    produce("asg_gerrant_cook_anchovies", GERRANT, ITEM_ANCHOVIES, "cooked anchovies", 5, 12, SkillId.Cooking, 1, "easy"),
    produce("asg_gerrant_cook_trout", GERRANT, ITEM_TROUT, "cooked trout", 5, 15, SkillId.Cooking, 15, "medium"),
    produce("asg_gerrant_cook_salmon", GERRANT, ITEM_SALMON, "cooked salmon", 5, 12, SkillId.Cooking, 25, "medium"),
    speak("asg_gerrant_tobias", GERRANT, TOBIAS, "Captain Tobias", 30),
    speak("asg_gerrant_wydin", GERRANT, WYDIN, "Wydin", 20),
    deliver("asg_gerrant_to_wydin", GERRANT, WYDIN, "Wydin", 20),
    deliver("asg_gerrant_to_tobias", GERRANT, TOBIAS, "Captain Tobias", 30),
    kill("asg_gerrant_ducks", GERRANT, AsgCombat.Ducks, "ducks", 5, 15, CombatMonsterCb.Duck, "very_easy"),
    kill("asg_gerrant_rats", GERRANT, AsgCombat.Rats, "rats", 5, 12, CombatMonsterCb.Rat, "very_easy"),
    kill("asg_gerrant_hobgoblins", GERRANT, AsgCombat.Hobgoblins, "hobgoblins", 3, 8, CombatMonsterCb.Hobgoblin, "medium"),
    visit("asg_gerrant_docks", GERRANT, GERRANT, AsgAreas.PortSarimDocks, "the fishing spots by the docks", 20),

    // ——— Hetty (herblore / magic) ———
    gather("asg_hetty_eye", HETTY, ITEM_EYE_OF_NEWT, "eyes of newt", 3, 10, SkillId.Herblore, 1, "easy"),
    gather("asg_hetty_onion", HETTY, ITEM_ONION, "onions", 5, 12, SkillId.Farming, 1, "very_easy"),
    gather("asg_hetty_vials", HETTY, ITEM_VIAL_WATER, "vials of water", 3, 10, SkillId.Herblore, 1, "very_easy"),
    gather("asg_hetty_ashes", HETTY, ITEM_ASHES, "ashes", 5, 12, SkillId.Firemaking, 1, "easy"),
    gather("asg_hetty_air", HETTY, ITEM_AIR_RUNE, "air runes", 15, 40, SkillId.Magic, 1, "easy"),
    produce("asg_hetty_attack_pot", HETTY, ITEM_ATTACK_POTION3, "attack potions", 1, 3, SkillId.Herblore, 3, "easy"),
    speak("asg_hetty_betty", HETTY, BETTY, "Betty", 80),
    speak("asg_hetty_phials", HETTY, PHIALS, "Phials", 30),
    speak("asg_hetty_sanfew", HETTY, SANFEW, "Sanfew", 280),
    deliver("asg_hetty_to_betty", HETTY, BETTY, "Betty", 80),
    deliver("asg_hetty_to_sanfew", HETTY, SANFEW, "Sanfew", 280),
    kill("asg_hetty_rats", HETTY, AsgCombat.Rats, "rats", 5, 15, CombatMonsterCb.Rat, "very_easy"),
    kill("asg_hetty_spiders", HETTY, AsgCombat.Spiders, "spiders", 5, 12, CombatMonsterCb.Spider, "easy"),
    kill("asg_hetty_imps", HETTY, AsgCombat.Imps, "imps", 3, 8, CombatMonsterCb.Imp, "easy"),
    kill("asg_hetty_highwaymen", HETTY, AsgCombat.Highwaymen, "highwaymen", 3, 8, CombatMonsterCb.Highwayman, "medium"),
    visit("asg_hetty_port", HETTY, HETTY, AsgAreas.PortSarim, "Port Sarim", 80),

    // ——— Wyson the Gardener (woodcutting / farming) ———
    gather("asg_wyson_logs", WYSON, ITEM_LOGS, "logs", 5, 20, SkillId.Woodcutting, 1, "easy", false),
    gather("asg_wyson_oak", WYSON, ITEM_OAK_LOGS, "oak logs", 5, 15, SkillId.Woodcutting, 15, "medium", false),
    gather("asg_wyson_potato", WYSON, ITEM_POTATO, "potatoes", 5, 15, SkillId.Farming, 1, "very_easy"),
    gather("asg_wyson_onion", WYSON, ITEM_ONION, "onions", 5, 12, SkillId.Farming, 1, "very_easy"),
    gather("asg_wyson_cabbage", WYSON, ITEM_CABBAGE, "cabbages", 5, 12, SkillId.Farming, 1, "very_easy"),
    gather("asg_wyson_eggs", WYSON, ITEM_EGG, "eggs", 3, 10, SkillId.Cooking, 1, "very_easy"),
    gather("asg_wyson_milk", WYSON, ITEM_BUCKET_MILK, "buckets of milk", 2, 8, SkillId.Cooking, 1, "very_easy"),
    speak("asg_wyson_squire", WYSON, SQ, "the Squire", 60),
    speak("asg_wyson_cassie", WYSON, CASSIE, "Cassie", 50),
    speak("asg_wyson_hair", WYSON, HAIR, "the Hairdresser", 50),
    deliver("asg_wyson_to_squire", WYSON, SQ, "the Squire", 60),
    deliver("asg_wyson_to_kaqe", WYSON, KAQE, "Kaqemeex", 160),
    visit("asg_wyson_park", WYSON, WYSON, AsgAreas.FaladorPark, "Falador Park", 20),
    visit("asg_wyson_crafting", WYSON, WYSON, AsgAreas.CraftingGuild, "the Crafting Guild", 120),
    kill("asg_wyson_ducks", WYSON, AsgCombat.Ducks, "ducks in the park", 5, 15, CombatMonsterCb.Duck, "very_easy"),
    kill("asg_wyson_imps", WYSON, AsgCombat.Imps, "imps", 3, 8, CombatMonsterCb.Imp, "easy"),
    kill("asg_wyson_chickens", WYSON, AsgCombat.Chickens, "chickens", 5, 12, CombatMonsterCb.Chicken, "very_easy"),
    kill("asg_wyson_guards", WYSON, AsgCombat.Guards, "Falador guards", 3, 10, CombatMonsterCb.Guard, "medium"),

    // ——— Phials (courier / utility) ———
    speak("asg_phials_speak_hetty", PHIALS, HETTY, "Hetty", 30),
    speak("asg_phials_speak_brian", PHIALS, BRIAN, "Brian", 100),
    speak("asg_phials_speak_wydin", PHIALS, WYDIN, "Wydin", 90),
    speak("asg_phials_speak_tobias", PHIALS, TOBIAS, "Captain Tobias", 90),
    speak("asg_phials_speak_squire", PHIALS, SQ, "the Squire", 180),
    deliver("asg_phials_letter_hetty", PHIALS, HETTY, "Hetty", 30),
    deliver("asg_phials_letter_betty", PHIALS, BETTY, "Betty", 90),
    deliver("asg_phials_letter_doric", PHIALS, DORIC, "Doric", 280),
    deliver("asg_phials_letter_amik", PHIALS, AMIK, "Sir Amik Varze", 200),
    deliver("asg_phials_letter_sanfew", PHIALS, SANFEW, "Sanfew", 260),
    visit("asg_phials_port", PHIALS, PHIALS, AsgAreas.PortSarim, "Port Sarim", 80),
    visit("asg_phials_falador", PHIALS, PHIALS, AsgAreas.FaladorSquare, "Falador", 180),
    visit("asg_phials_taverley", PHIALS, PHIALS, AsgAreas.Taverley, "Taverley", 250),
    gather("asg_phials_logs", PHIALS, ITEM_LOGS, "logs", 5, 15, SkillId.Woodcutting, 1, "easy", false),
    gather("asg_phials_planks", PHIALS, ITEM_PLANK, "planks", 3, 10, SkillId.Construction, 1, "easy"),
    kill("asg_phials_rats", PHIALS, AsgCombat.Rats, "rats", 5, 15, CombatMonsterCb.Rat, "very_easy"),
    kill("asg_phials_imps", PHIALS, AsgCombat.Imps, "imps", 3, 8, CombatMonsterCb.Imp, "easy"),
    kill("asg_phials_guards", PHIALS, AsgCombat.Guards, "guards", 3, 8, CombatMonsterCb.Guard, "medium"),
    kill("asg_phials_goblins", PHIALS, AsgCombat.Goblins, "goblins", 5, 12, CombatMonsterCb.Goblin, "easy"),

    // ——— League task overlaps ———
    visit("asg_league_falador_agility", SQ, SQ, AsgAreas.FaladorAgility, "the Falador rooftop course area", 40),
    visit(
        "asg_league_falador_agility_amik",
        AMIK,
        AMIK,
        AsgAreas.FaladorAgility,
        "the Falador rooftop course area",
        50,
    ),
    visit("asg_league_crafting_guild", WYSON, WYSON, AsgAreas.CraftingGuild, "the Crafting Guild", 120),
    visit(
        "asg_league_crafting_guild_doric",
        DORIC,
        DORIC,
        AsgAreas.CraftingGuild,
        "the Crafting Guild",
        160,
    ),
    visit(
        "asg_league_taverley_dungeon",
        SANFEW,
        SANFEW,
        AsgAreas.TaverleyDungeonEntrance,
        "the Taverley Dungeon entrance",
        40,
    ),
    visit(
        "asg_league_taverley_dungeon_kaqe",
        KAQE,
        KAQE,
        AsgAreas.TaverleyDungeonEntrance,
        "the Taverley Dungeon entrance",
        80,
    ),
    visit("asg_league_warriors_guild", DENULTH, DENULTH, AsgAreas.WarriorsGuild, "the Warriors' Guild", 80),
    visit("asg_league_heroes_guild", DENULTH, DENULTH, AsgAreas.HeroesGuild, "the Heroes' Guild", 60),
    visit(
        "asg_league_heroes_guild_achietties",
        ACHIETTIES,
        ACHIETTIES,
        AsgAreas.HeroesGuild,
        "the Heroes' Guild",
        20,
    ),
    visit("asg_league_air_ruins", BETTY, BETTY, AsgAreas.AirAltarRuins, "the Air Altar ruins", 100),
    visit("asg_league_body_ruins", BETTY, BETTY, AsgAreas.BodyAltarRuins, "the Body Altar ruins", 260),
    visit("asg_league_mind_ruins", TIFFY, TIFFY, AsgAreas.MindAltarRuins, "the Mind Altar ruins", 200),
    kill(
        "asg_league_troll",
        DENULTH,
        AsgCombat.MountainTrolls,
        "a mountain troll in Asgarnia",
        1,
        5,
        CombatMonsterCb.MountainTroll,
        "hard",
    ),
    kill(
        "asg_league_troll_dunstan",
        DUNSTAN,
        AsgCombat.MountainTrolls,
        "a mountain troll in Asgarnia",
        1,
        5,
        CombatMonsterCb.MountainTroll,
        "hard",
    ),
    kill(
        "asg_league_black_knight",
        AMIK,
        AsgCombat.BlackKnights,
        "a Black Knight",
        1,
        5,
        CombatMonsterCb.BlackKnight,
        "medium",
    ),
    kill(
        "asg_league_hill_giant",
        DORIC,
        AsgCombat.HillGiants,
        "a hill giant in Taverley Dungeon",
        1,
        5,
        CombatMonsterCb.HillGiant,
        "medium",
    ),
    kill(
        "asg_league_guard",
        SQ,
        AsgCombat.Guards,
        "a Falador guard",
        1,
        5,
        CombatMonsterCb.Guard,
        "medium",
    ),
    kill(
        "asg_league_ice_warrior",
        TIFFY,
        AsgCombat.IceWarriors,
        "an ice warrior",
        1,
        3,
        CombatMonsterCb.IceWarrior,
        "hard",
    ),
    gather(
        "asg_league_pure_essence",
        BETTY,
        ITEM_PURE_ESSENCE,
        "pure essence",
        15,
        25,
        SkillId.Mining,
        1,
        "medium",
        false,
    ),
    gather(
        "asg_league_air_runes",
        BETTY,
        ITEM_AIR_RUNE,
        "air runes",
        20,
        50,
        SkillId.Runecraft,
        1,
        "easy",
    ),
    skillAct(
        "asg_league_cook_range",
        WYDIN,
        ["cook:range"],
        AsgAreas.PortSarim,
        "Cook food on a range in Port Sarim",
        SkillId.Cooking,
        1,
        "easy",
        { amount: [1, 5], objectNames: ["Cooking range", "Range"] },
    ),
    produce("asg_league_bread_wydin", WYDIN, ITEM_BREAD, "bread", 3, 10, SkillId.Cooking, 1, "easy"),
    speak("asg_league_makeover", PHIALS, MAKEOVER, "the Make-over Mage", 100),
    visit("asg_league_makeover_area", MAKEOVER, MAKEOVER, AsgAreas.FaladorSquare, "west of Falador", 40),
];

/** Tasks excluded from the Asgarnia pool (parity / spawn limits). */
export const ASGARNIA_EXCLUDED_NOTES = [
    "God Wars / Cerberus / Giant Mole kill counts — boss favours deferred",
    "Law altar Entrana crafting — requires Entrana access rules",
    "Motherlode Mine golden nuggets — specialised skilling content",
    "Pest Control / Void Knight tasks — minigame system",
    "Ceril Carnillean — Kandarin spawn, not Asgarnia",
    "Black Knight Titan — quest instance, not overworld",
];
