export const ITEM_SPAWNER_MODAL_GROUP_ID = 30002;

export const ITEM_SPAWNER_MODAL_COMPONENT_ROOT = 0;
export const ITEM_SPAWNER_MODAL_COMPONENT_FRAME = 1;
export const ITEM_SPAWNER_MODAL_COMPONENT_TITLE = 2;
export const ITEM_SPAWNER_MODAL_COMPONENT_BODY = 3;
export const ITEM_SPAWNER_MODAL_COMPONENT_QUERY = 4;
export const ITEM_SPAWNER_MODAL_COMPONENT_SUMMARY = 5;
export const ITEM_SPAWNER_MODAL_COMPONENT_HELPER = 6;
export const ITEM_SPAWNER_MODAL_COMPONENT_CLOSE = 7;
export const ITEM_SPAWNER_MODAL_COMPONENT_RESULTS_VIEW = 8;
export const ITEM_SPAWNER_MODAL_COMPONENT_RESULTS_SCROLLBAR = 9;
export const ITEM_SPAWNER_MODAL_COMPONENT_SEARCH_BACKGROUND = 10;

export const ITEM_SPAWNER_MODAL_SLOT_COLUMNS = 8;
export const ITEM_SPAWNER_MODAL_VISIBLE_ROW_COUNT = 3;
export const ITEM_SPAWNER_MODAL_VIRTUAL_ROW_COUNT = 4;
export const ITEM_SPAWNER_MODAL_RESULT_SLOT_COUNT =
    ITEM_SPAWNER_MODAL_SLOT_COLUMNS * ITEM_SPAWNER_MODAL_VIRTUAL_ROW_COUNT;
export const ITEM_SPAWNER_MODAL_COMPONENT_SLOT_BACKGROUND_START = 20;
export const ITEM_SPAWNER_MODAL_COMPONENT_SLOT_ICON_START = 100;
