export const SMITHING_BAR_MODAL_GROUP_ID = 30001;

export const SMITHING_BAR_MODAL_COMPONENT_ROOT = 0;
export const SMITHING_BAR_MODAL_COMPONENT_FRAME = 1;
export const SMITHING_BAR_MODAL_COMPONENT_TITLE = 2;
export const SMITHING_BAR_MODAL_COMPONENT_BODY = 3;
export const SMITHING_BAR_MODAL_COMPONENT_CURRENT = 4;

export const SMITHING_BAR_MODAL_COMPONENT_BRONZE = 10;
export const SMITHING_BAR_MODAL_COMPONENT_IRON = 11;
export const SMITHING_BAR_MODAL_COMPONENT_STEEL = 12;
export const SMITHING_BAR_MODAL_COMPONENT_MITHRIL = 13;
export const SMITHING_BAR_MODAL_COMPONENT_ADAMANT = 14;
export const SMITHING_BAR_MODAL_COMPONENT_RUNE = 15;
export const SMITHING_BAR_MODAL_COMPONENT_LOVAKITE = 16;

export const SMITHING_BAR_MODAL_COMPONENT_BRONZE_ICON = 30;
export const SMITHING_BAR_MODAL_COMPONENT_IRON_ICON = 31;
export const SMITHING_BAR_MODAL_COMPONENT_STEEL_ICON = 32;
export const SMITHING_BAR_MODAL_COMPONENT_MITHRIL_ICON = 33;
export const SMITHING_BAR_MODAL_COMPONENT_ADAMANT_ICON = 34;
export const SMITHING_BAR_MODAL_COMPONENT_RUNE_ICON = 35;
export const SMITHING_BAR_MODAL_COMPONENT_LOVAKITE_ICON = 36;

export const SMITHING_BAR_MODAL_COMPONENT_BRONZE_TEXT = 40;
export const SMITHING_BAR_MODAL_COMPONENT_IRON_TEXT = 41;
export const SMITHING_BAR_MODAL_COMPONENT_STEEL_TEXT = 42;
export const SMITHING_BAR_MODAL_COMPONENT_MITHRIL_TEXT = 43;
export const SMITHING_BAR_MODAL_COMPONENT_ADAMANT_TEXT = 44;
export const SMITHING_BAR_MODAL_COMPONENT_RUNE_TEXT = 45;
export const SMITHING_BAR_MODAL_COMPONENT_LOVAKITE_TEXT = 46;

export const SMITHING_BAR_MODAL_COMPONENT_CLOSE = 20;
