/**
 * Auto-generated from OSRS wiki Quests/List (Difficulty × Length favour costs).
 * Source: https://oldschool.runescape.wiki/w/Quests/List
 * Do not hand-edit — regenerate with:
 *   npx tsx scripts/cache/parse-quest-wiki-costs.ts
 *   npx tsx scripts/cache/generate-quest-favour-costs-data.ts
 */

export type QuestWikiDifficulty =
    | "Novice"
    | "Intermediate"
    | "Experienced"
    | "Master"
    | "Grandmaster"
    | "Special";

export type QuestWikiLength =
    | "Very Short"
    | "Short"
    | "Medium"
    | "Long"
    | "Very Long";

export type QuestFavourCostDef = {
    /** Wiki display name. */
    wikiName: string;
    /** Matching cache questCompletions.name when known. */
    cacheName?: string;
    difficulty: QuestWikiDifficulty;
    length: QuestWikiLength;
    /** favourCost = difficultyMult × lengthMult */
    favourCost: number;
    source: "f2p" | "members" | "miniquest";
};

/** Wiki difficulty → cost multiplier. */
export const QUEST_DIFFICULTY_MULT = {
    "Novice": 1,
    "Intermediate": 3,
    "Experienced": 5,
    "Master": 10,
    "Grandmaster": 15,
    "Special": 20,
} as const satisfies Record<QuestWikiDifficulty, number>;

/** Wiki length → cost multiplier. */
export const QUEST_LENGTH_MULT = {
    "Very Short": 1,
    "Short": 2,
    "Medium": 3,
    "Long": 4,
    "Very Long": 5,
} as const satisfies Record<QuestWikiLength, number>;

export const QUEST_FAVOUR_COSTS: readonly QuestFavourCostDef[] = [
    { wikiName: "The Ides of Milk", cacheName: "Ides of Milk, The", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Learning the Ropes", cacheName: "Learning the Ropes", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "Below Ice Mountain", cacheName: "Below Ice Mountain", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "X Marks the Spot", cacheName: "X Marks the Spot", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "The Corsair Curse", cacheName: "Corsair Curse, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "f2p" },
    { wikiName: "Misthalin Mystery", cacheName: "Misthalin Mystery", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Rune Mysteries", cacheName: "Rune Mysteries", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Dragon Slayer I", cacheName: "Dragon Slayer I", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "f2p" },
    { wikiName: "Pirate's Treasure", cacheName: "Pirate's Treasure", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "Goblin Diplomacy", cacheName: "Goblin Diplomacy", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "The Knight's Sword", cacheName: "Knight's Sword, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "f2p" },
    { wikiName: "Witch's Potion", cacheName: "Witch's Potion", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "Black Knights' Fortress", cacheName: "Black Knights' Fortress", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "f2p" },
    { wikiName: "Doric's Quest", cacheName: "Doric's Quest", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "Prince Ali Rescue", cacheName: "Prince Ali Rescue", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Imp Catcher", cacheName: "Imp Catcher", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Vampyre Slayer", cacheName: "Vampyre Slayer", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "f2p" },
    { wikiName: "Ernest the Chicken", cacheName: "Ernest the Chicken", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "The Restless Ghost", cacheName: "Restless Ghost, The", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Sheep Shearer", cacheName: "Sheep Shearer", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "Shield of Arrav", cacheName: "Shield of Arrav", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Demon Slayer", cacheName: "Demon Slayer", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Romeo & Juliet", cacheName: "Romeo & Juliet", difficulty: "Novice", length: "Short", favourCost: 2, source: "f2p" },
    { wikiName: "Cook's Assistant", cacheName: "Cook's Assistant", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "f2p" },
    { wikiName: "Druidic Ritual", cacheName: "Druidic Ritual", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Lost City", cacheName: "Lost City", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Witch's House", cacheName: "Witch's House", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "members" },
    { wikiName: "Merlin's Crystal", cacheName: "Merlin's Crystal", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Heroes' Quest", cacheName: "Heroes' Quest", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Scorpion Catcher", cacheName: "Scorpion Catcher", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Family Crest", cacheName: "Family Crest", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Fishing Contest", cacheName: "Fishing Contest", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Tribal Totem", cacheName: "Tribal Totem", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "members" },
    { wikiName: "Monk's Friend", cacheName: "Monk's Friend", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Temple of Ikov", cacheName: "Temple of Ikov", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Clock Tower", cacheName: "Clock Tower", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Holy Grail", cacheName: "Holy Grail", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Tree Gnome Village", cacheName: "Tree Gnome Village", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Fight Arena", cacheName: "Fight Arena", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Hazeel Cult", cacheName: "Hazeel Cult", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Sheep Herder", cacheName: "Sheep Herder", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Plague City", cacheName: "Plague City", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Sea Slug", cacheName: "Sea Slug", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Waterfall Quest", cacheName: "Waterfall Quest", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Jungle Potion", cacheName: "Jungle Potion", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "The Grand Tree", cacheName: "Grand Tree, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Underground Pass", cacheName: "Underground Pass", difficulty: "Experienced", length: "Long", favourCost: 20, source: "members" },
    { wikiName: "Observatory Quest", cacheName: "Observatory Quest", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Tourist Trap", cacheName: "Tourist Trap, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Watchtower", cacheName: "Watchtower", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Dwarf Cannon", cacheName: "Dwarf Cannon", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Murder Mystery", cacheName: "Murder Mystery", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "The Dig Site", cacheName: "Dig Site, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Gertrude's Cat", cacheName: "Gertrude's Cat", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Legends' Quest", cacheName: "Legends' Quest", difficulty: "Master", length: "Long", favourCost: 40, source: "members" },
    { wikiName: "Death Plateau", cacheName: "Death Plateau", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Eadgar's Ruse", cacheName: "Eadgar's Ruse", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Big Chompy Bird Hunting", cacheName: "Big Chompy Bird Hunting", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Elemental Workshop I", cacheName: "Elemental Workshop I", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Nature Spirit", cacheName: "Nature Spirit", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Priest in Peril", cacheName: "Priest in Peril", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Regicide", cacheName: "Regicide", difficulty: "Experienced", length: "Long", favourCost: 20, source: "members" },
    { wikiName: "Tai Bwo Wannai Trio", cacheName: "Tai Bwo Wannai Trio", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Troll Stronghold", cacheName: "Troll Stronghold", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Shades of Mort'ton", cacheName: "Shades of Mort'ton", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Fremennik Trials", cacheName: "Fremennik Trials, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Horror from the Deep", cacheName: "Horror from the Deep", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Throne of Miscellania", cacheName: "Throne of Miscellania", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Monkey Madness I", cacheName: "Monkey Madness I", difficulty: "Master", length: "Long", favourCost: 40, source: "members" },
    { wikiName: "Haunted Mine", cacheName: "Haunted Mine", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "Troll Romance", cacheName: "Troll Romance", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "In Search of the Myreque", cacheName: "In Search of the Myreque", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Creature of Fenkenstrain", cacheName: "Creature of Fenkenstrain", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Roving Elves", cacheName: "Roving Elves", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "Ghosts Ahoy", cacheName: "Ghosts Ahoy", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "One Small Favour", cacheName: "One Small Favour", difficulty: "Experienced", length: "Long", favourCost: 20, source: "members" },
    { wikiName: "Mountain Daughter", cacheName: "Mountain Daughter", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Between a Rock...", cacheName: "Between a Rock...", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "The Feud", cacheName: "Feud, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "The Golem", cacheName: "Golem, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Desert Treasure I", cacheName: "Desert Treasure I", difficulty: "Master", length: "Long", favourCost: 40, source: "members" },
    { wikiName: "Icthlarin's Little Helper", cacheName: "Icthlarin's Little Helper", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Tears of Guthix", cacheName: "Tears of Guthix", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "members" },
    { wikiName: "The Lost Tribe", cacheName: "Lost Tribe, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Giant Dwarf", cacheName: "Giant Dwarf, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Recruitment Drive", cacheName: "Recruitment Drive", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Mourning's End Part I", cacheName: "Mourning's End Part I", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Forgettable Tale...", cacheName: "Forgettable Tale...", difficulty: "Intermediate", length: "Long", favourCost: 12, source: "members" },
    { wikiName: "Garden of Tranquillity", cacheName: "Garden of Tranquillity", difficulty: "Intermediate", length: "Long", favourCost: 12, source: "members" },
    { wikiName: "A Tail of Two Cats", cacheName: "Tail of Two Cats, A", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Wanted!", cacheName: "Wanted!", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Mourning's End Part II", cacheName: "Mourning's End Part II", difficulty: "Master", length: "Long", favourCost: 40, source: "members" },
    { wikiName: "Rum Deal", cacheName: "Rum Deal", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Shadow of the Storm", cacheName: "Shadow of the Storm", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Making History", cacheName: "Making History", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Ratcatchers", cacheName: "Ratcatchers", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Spirits of the Elid", cacheName: "Spirits of the Elid", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Devious Minds", cacheName: "Devious Minds", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "The Hand in the Sand", cacheName: "Hand in the Sand, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Enakhra's Lament", cacheName: "Enakhra's Lament", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Cabin Fever", cacheName: "Cabin Fever", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "Fairytale I - Growing Pains", cacheName: "Fairytale I - Growing Pains", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Recipe for Disaster", cacheName: "Recipe for Disaster", difficulty: "Special", length: "Very Long", favourCost: 100, source: "members" },
    { wikiName: "In Aid of the Myreque", cacheName: "In Aid of the Myreque", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "A Soul's Bane", cacheName: "Soul's Bane, A", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Rag and Bone Man I", cacheName: "Rag and Bone Man I", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Swan Song", cacheName: "Swan Song", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Royal Trouble", cacheName: "Royal Trouble", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Death to the Dorgeshuun", cacheName: "Death to the Dorgeshuun", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Fairytale II - Cure a Queen", cacheName: "Fairytale II - Cure a Queen", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Lunar Diplomacy", cacheName: "Lunar Diplomacy", difficulty: "Experienced", length: "Long", favourCost: 20, source: "members" },
    { wikiName: "The Eyes of Glouphrie", cacheName: "Eyes of Glouphrie, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Darkness of Hallowvale", cacheName: "Darkness of Hallowvale", difficulty: "Experienced", length: "Long", favourCost: 20, source: "members" },
    { wikiName: "The Slug Menace", cacheName: "Slug Menace, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Elemental Workshop II", cacheName: "Elemental Workshop II", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "My Arm's Big Adventure", cacheName: "My Arm's Big Adventure", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Enlightened Journey", cacheName: "Enlightened Journey", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Eagles' Peak", cacheName: "Eagles' Peak", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Animal Magnetism", cacheName: "Animal Magnetism", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Contact!", cacheName: "Contact!", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "Cold War", cacheName: "Cold War", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "The Fremennik Isles", cacheName: "Fremennik Isles, The", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "The Great Brain Robbery", cacheName: "Great Brain Robbery, The", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "What Lies Below", cacheName: "What Lies Below", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Olaf's Quest", cacheName: "Olaf's Quest", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Another Slice of H.A.M.", cacheName: "Another Slice of H.A.M.", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Dream Mentor", cacheName: "Dream Mentor", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Grim Tales", cacheName: "Grim Tales", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "King's Ransom", cacheName: "King's Ransom", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Shilo Village", cacheName: "Shilo Village", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Biohazard", cacheName: "Biohazard", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Tower of Life", cacheName: "Tower of Life", difficulty: "Novice", length: "Medium", favourCost: 3, source: "members" },
    { wikiName: "Rag and Bone Man II", cacheName: "Rag and Bone Man II", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Land of the Goblins", cacheName: "Land of the Goblins", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "While Guthix Sleeps", cacheName: "While Guthix Sleeps", difficulty: "Grandmaster", length: "Very Long", favourCost: 75, source: "members" },
    { wikiName: "Zogre Flesh Eaters", cacheName: "Zogre Flesh Eaters", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Monkey Madness II", cacheName: "Monkey Madness II", difficulty: "Grandmaster", length: "Very Long", favourCost: 75, source: "members" },
    { wikiName: "Client of Kourend", cacheName: "Client of Kourend", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "The Queen of Thieves", cacheName: "Queen of Thieves, The", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "members" },
    { wikiName: "Bone Voyage", cacheName: "Bone Voyage", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Dragon Slayer II", cacheName: "Dragon Slayer II", difficulty: "Grandmaster", length: "Very Long", favourCost: 75, source: "members" },
    { wikiName: "The Depths of Despair", cacheName: "Depths of Despair, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Recipe for Disaster/Another Cook's Quest", cacheName: "Recipe for Disaster Another Cook's Quest", difficulty: "Special", length: "Short", favourCost: 40, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing the Goblin generals", cacheName: "Recipe for Disaster Goblins", difficulty: "Special", length: "Short", favourCost: 40, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing the Mountain Dwarf", cacheName: "Recipe for Disaster Dwarf", difficulty: "Special", length: "Short", favourCost: 40, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing Evil Dave", cacheName: "Recipe for Disaster Dave", difficulty: "Special", length: "Medium", favourCost: 60, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing Pirate Pete", cacheName: "Recipe for Disaster Pirate", difficulty: "Special", length: "Medium", favourCost: 60, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing the Lumbridge Guide", cacheName: "Recipe for Disaster Lumbridge Guide", difficulty: "Special", length: "Short", favourCost: 40, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing Sir Amik Varze", cacheName: "Recipe for Disaster Amik Varze", difficulty: "Special", length: "Medium", favourCost: 60, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing King Awowogei", cacheName: "Recipe for Disaster Awowogei", difficulty: "Special", length: "Long", favourCost: 80, source: "members" },
    { wikiName: "Recipe for Disaster/Freeing Skrach Uglogwee", cacheName: "Recipe for Disaster Uglogwee", difficulty: "Special", length: "Medium", favourCost: 60, source: "members" },
    { wikiName: "A Taste of Hope", cacheName: "Taste of Hope, A", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Tale of the Righteous", cacheName: "Tale of the Righteous", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Making Friends with My Arm", cacheName: "Making Friends with My Arm", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Recipe for Disaster/Defeating the Culinaromancer", cacheName: "Recipe for Disaster Culinaromancer", difficulty: "Special", length: "Short", favourCost: 40, source: "members" },
    { wikiName: "Song of the Elves", cacheName: "Song of the Elves", difficulty: "Grandmaster", length: "Very Long", favourCost: 75, source: "members" },
    { wikiName: "The Ascent of Arceuus", cacheName: "Ascent of Arceuus, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Forsaken Tower", cacheName: "Forsaken Tower, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Fremennik Exiles", cacheName: "Fremennik Exiles, The", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "The Curse of Arrav", cacheName: "Curse of Arrav, The", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Defender of Varrock", cacheName: "Defender of Varrock", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Sins of the Father", cacheName: "Sins of the Father", difficulty: "Master", length: "Long", favourCost: 40, source: "members" },
    { wikiName: "A Kingdom Divided", cacheName: "Kingdom Divided, A", difficulty: "Experienced", length: "Long", favourCost: 20, source: "members" },
    { wikiName: "A Porcine of Interest", cacheName: "Porcine of Interest, A", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Getting Ahead", cacheName: "Getting Ahead", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "A Night at the Theatre", cacheName: "Night at the Theatre, A", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Beneath Cursed Sands", cacheName: "Beneath Cursed Sands", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Temple of the Eye", cacheName: "Temple of the Eye", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Path of Glouphrie", cacheName: "Path of Glouphrie, The", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Sleeping Giants", cacheName: "Sleeping Giants", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "members" },
    { wikiName: "The Garden of Death", cacheName: "Garden of Death, The", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Desert Treasure II - The Fallen Empire", cacheName: "Desert Treasure II - The Fallen Empire", difficulty: "Grandmaster", length: "Very Long", favourCost: 75, source: "members" },
    { wikiName: "Secrets of the North", cacheName: "Secrets of the North", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "Children of the Sun", cacheName: "Children of the Sun", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Perilous Moons", cacheName: "Perlious Moons", difficulty: "Master", length: "Medium", favourCost: 30, source: "members" },
    { wikiName: "The Ribbiting Tale of a Lily Pad Labour Dispute", cacheName: "Ribbiting Tale of a Lily Pad Labour Dispute, The", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "members" },
    { wikiName: "Twilight's Promise", cacheName: "Twilight's Promise", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "At First Light", cacheName: "At First Light", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "The Heart of Darkness", cacheName: "Heart of Darkness, The", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Death on the Isle", cacheName: "Death on the Isle", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "members" },
    { wikiName: "Meat and Greet", cacheName: "Meat and Greet", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "Ethically Acquired Antiquities", cacheName: "Ethically Acquired Antiquities", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "The Blood Moon Rises", difficulty: "Grandmaster", length: "Very Long", favourCost: 75, source: "members" },
    { wikiName: "The Final Dawn", cacheName: "Final Dawn, The", difficulty: "Master", length: "Long", favourCost: 40, source: "members" },
    { wikiName: "Pandemonium", cacheName: "Pandemonium", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Prying Times", cacheName: "Prying Times", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Current Affairs", cacheName: "Current Affairs", difficulty: "Novice", length: "Short", favourCost: 2, source: "members" },
    { wikiName: "Troubled Tortugans", cacheName: "Troubled Tortugans", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "The Red Reef", cacheName: "Red Reef, The", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "members" },
    { wikiName: "Shadows of Custodia", cacheName: "Shadows of Custodia", difficulty: "Experienced", length: "Short", favourCost: 10, source: "members" },
    { wikiName: "Scrambled!", cacheName: "Scrambled!", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "members" },
    { wikiName: "Alfred Grimhand's Barcrawl", cacheName: "Alfred Grimhand's Barcrawl", difficulty: "Novice", length: "Medium", favourCost: 3, source: "miniquest" },
    { wikiName: "Enter the Abyss", cacheName: "Enter the Abyss", difficulty: "Intermediate", length: "Very Short", favourCost: 3, source: "miniquest" },
    { wikiName: "The General's Shadow", cacheName: "General's Shadow, The", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "miniquest" },
    { wikiName: "Barbarian Training", cacheName: "Barbarian Training", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "miniquest" },
    { wikiName: "Skippy and the Mogres", cacheName: "Skippy and the Mogres", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "miniquest" },
    { wikiName: "Curse of the Empty Lord", cacheName: "Curse of the Empty Lord", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "miniquest" },
    { wikiName: "Lair of Tarn Razorlor", cacheName: "Lair of Tarn Razorlor", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "miniquest" },
    { wikiName: "Bear Your Soul", cacheName: "Bear Your Soul", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "miniquest" },
    { wikiName: "The Enchanted Key", cacheName: "Enchanted Key, The", difficulty: "Intermediate", length: "Medium", favourCost: 9, source: "miniquest" },
    { wikiName: "Mage Arena I", cacheName: "Mage Arena I", difficulty: "Experienced", length: "Short", favourCost: 10, source: "miniquest" },
    { wikiName: "Family Pest", cacheName: "Family Pest", difficulty: "Intermediate", length: "Short", favourCost: 6, source: "miniquest" },
    { wikiName: "Mage Arena II", cacheName: "Mage Arena II", difficulty: "Master", length: "Medium", favourCost: 30, source: "miniquest" },
    { wikiName: "In Search of Knowledge", cacheName: "In Search of Knowledge", difficulty: "Experienced", length: "Medium", favourCost: 15, source: "miniquest" },
    { wikiName: "Daddy's Home", cacheName: "Daddy's Home", difficulty: "Novice", length: "Short", favourCost: 2, source: "miniquest" },
    { wikiName: "The Frozen Door", cacheName: "Frozen Door, The", difficulty: "Master", length: "Short", favourCost: 20, source: "miniquest" },
    { wikiName: "Hopespear's Will", cacheName: "Hopespear's Will", difficulty: "Master", length: "Short", favourCost: 20, source: "miniquest" },
    { wikiName: "Into the Tombs", cacheName: "Into the Tombs", difficulty: "Master", length: "Medium", favourCost: 30, source: "miniquest" },
    { wikiName: "His Faithful Servants", cacheName: "His Faithful Servants", difficulty: "Experienced", length: "Very Short", favourCost: 5, source: "miniquest" },
    { wikiName: "Vale Totems", cacheName: "Vale Totems", difficulty: "Novice", length: "Very Short", favourCost: 1, source: "miniquest" },
];
